export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";

export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAIL = "REGISTER_USER_FAIL";

export const LOAD_USER_REQUEST = "LOAD_USER_REQUEST";
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS";
export const LOAD_USER_FAIL = "LOAD_USER_FAIL";


export const LOAD_SERVICE_REQUEST = "LOAD_SERVICE_REQUEST";
export const LOAD_SERVICE_SUCCESS = "LOAD_SERVICE_SUCCESS";
export const LOAD_SERVICE_FAIL = "LOAD_SERVICE_FAIL";

export const CREATE_SERVICE_REQUEST = "CREATE_SERVICE_REQUEST";
export const CREATE_SERVICE_SUCCESS = "CREATE_SERVICE_SUCCESS";
export const CREATE_SERVICE_FAIL = "CREATE_SERVICE_FAIL";


export const ADMIN_INQUIRYS_REQUEST = "ADMIN_INQUIRYS_REQUEST";
export const ADMIN_INQUIRYS_SUCCESS = "ADMIN_INQUIRYS_SUCCESS";
export const ADMIN_INQUIRYS_FAIL = "ADMIN_INQUIRYS_FAIL";

export const GET_INQUIRYS_REQUEST = "GET_INQUIRYS_REQUEST";
export const GET_INQUIRYS_SUCCESS = "GET_INQUIRYS_SUCCESS";
export const GET_INQUIRYS_FAIL = "GET_INQUIRYS_FAIL";

export const CREATE_INQUIYT_REQUEST = "CREATE_INQUIRY_REQUEST";
export const CREATE_INQUIYT_SUCCESS = "CREATE_INQUIRY_SUCCESS";
export const CREATE_INQUIYT_FAIL = "CREATE_INQUIRY_FAIL";
export const CREATE_INQUIYT_RESET = "CREATE_INQUIRY_RESET";

export const UPDATE_INQUIYT_REQUEST = "UPDATE_INQUIRY_REQUEST";
export const UPDATE_INQUIYT_SUCCESS = "UPDATE_INQUIRY_SUCCESS";
export const UPDATE_INQUIYT_FAIL = "UPDATE_INQUIRY_FAIL";
export const UPDATE_INQUIYT_RESET = "UPDATE_INQUIRY_RESET";

export const GET_INQUIYT_FOR_DISPLAY_REQUEST = "GET_INQUIYT_FOR_DISPLAY_REQUEST";
export const GET_INQUIYT_FOR_DISPLAY_SUCCESS = "GET_INQUIYT_FOR_DISPLAY_SUCCESS";
export const GET_INQUIYT_FOR_DISPLAY_FAIL = "GET_INQUIYT_FOR_DISPLAY_FAIL";

export const GET_ALL_USERS_REQUEST = "GET_ALL_USERS_REQUEST";
export const GET_ALL_USERS_SUCCESS = "GET_ALL_USERS_SUCCESS";
export const GET_ALL_USERS_FAIL = "GET_ALL_USERS_FAIL";

export const GET_STATUS_REQUEST = "GET_STATUS_REQUEST";
export const GET_STATUS_SUCCESS = "GET_STATUS_SUCCESS";
export const GET_STATUS_FAIL = "GET_STATUS_FAIL";

export const SEND_EMAIL_REQUEST = "SEND_EMAIL_REQUEST";
export const SEND_EMAIL_SUCCESS = "SEND_EMAIL_SUCCESS";
export const SEND_EMAIL_FAIL = "SEND_EMAIL_FAIL";

export const FORGOT_PASSWORD_REQUEST = "FORGOT_PASSWORD_REQUEST";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_FAIL = "FORGOT_PASSWORD_FAIL";

export const RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAIL = "RESET_PASSWORD_FAIL";

export const SEND_EMAIL_STATUS_REQUEST = "SEND_EMAIL_STATUS_REQUEST";
export const SEND_EMAIL_STATUS_SUCCESS = "SEND_EMAIL_STATUS_SUCCESS";
export const SEND_EMAIL_STATUS_FAIL = "SEND_EMAIL_STATUS_FAIL";

export const CREATE_CLIENT_REQUEST = "CREATE_CLIENT_REQUEST";
export const CREATE_CLIENT_SUCCESS = "CREATE_CLIENT_SUCCESS";
export const CREATE_CLIENT_FAIL = "CREATE_CLIENT_FAIL";

export const GET_CLIENTS_REQUEST = "GET_CLIENTS_REQUEST";
export const GET_CLIENTS_SUCCESS = "GET_CLIENTS_SUCCESS";
export const GET_CLIENTS_FAIL = "GET_CLIENTS_FAIL";


















export const CLEAR_ERROR = "CLEAR_ERROR";